on: push

jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository
        uses: actions/checkout@v3

      - name: Say Hello
        id: hello
        uses: ./.github/actions/hello
        with:
          who-to-greet: "Jonathan"

      - name: Show time
        run: |
          echo "Time: ${{ steps.hello.outputs.time }}"