on: push

jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository
        uses: actions/checkout@v3

      - name: Test conditional
        run: |
          if [[ ${{ github.ref_name }}  == stage ]]; then
          echo "branch_name=stage" >> $GITHUB_ENV
          else
          echo "branch_name=prod" >> $GITHUB_ENV
          fi

      - name: Show branch name
        run: echo "${{ env.branch_name }}"

      - name: Say Hello
        id: hello
        uses: ./.github/actions/hello
        with:
          who-to-greet: "Jonathan"

      - name: Show time
        run: |
          echo "Time: ${{ steps.hello.outputs.time }}"

  check-env:
    needs: testing-action
    runs-on: ubuntu-latest
    steps:
      - name: Show env value
        run: |
          ENV_TYPE: `cat teste.txt`

          echo "${{ env.branch_name }}"
          echo "${{ env.ENV_TYPE }}"
